"""Regenerate MoonBit tests from checked-in Apache-2.0 fixtures; no network IO."""
import json
from pathlib import Path

root = Path(__file__).resolve().parent.parent
lines = [
    "// Derived from json-patch/json-patch-tests, Copyright 2014 The Authors.",
    "// SPDX-License-Identifier: Apache-2.0",
    "// Generated by scripts/generate_conformance.py. See THIRD_PARTY_NOTICES.md.",
]
count = 0


def literal(value):
    return json.dumps(json.dumps(value, ensure_ascii=False, separators=(",", ":")), ensure_ascii=False)


for filename in ["tests.json", "spec_tests.json"]:
    tests = json.loads((root / "tests" / "upstream" / filename).read_text(encoding="utf-8"))
    for index, case in enumerate(tests):
        if case.get("disabled") or "doc" not in case or "patch" not in case:
            continue
        if "expected" not in case and "error" not in case:
            continue
        request = {"command": "apply", "document": case["doc"], "patch": case["patch"]}
        lines += [
            "///|", f'test "upstream {filename} {index}" {{',
            f"  let response = @json.parse(run_json({literal(request)}))",
            '  guard response is Object(o) else { fail("response shape") }',
        ]
        if "error" in case:
            lines += ['  assert_eq(o["ok"], Json::boolean(false))']
        else:
            lines += ['  assert_eq(o["ok"], Json::boolean(true))',
                      f'  assert_eq(o["result"], @json.parse({literal(case["expected"])}))']
        lines += ["}", ""]
        count += 1

(root / "conformance_wbtest.mbt").write_text("\n".join(lines), encoding="utf-8")
print(f"Generated {count} enabled upstream cases. Run moon fmt next.")
